# Generated by Django 3.0.2 on 2020-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0003_onl_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onl',
            name='title',
        ),
        migrations.AddField(
            model_name='onl',
            name='month',
            field=models.CharField(blank=True, max_length=10, verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='onl',
            name='date',
            field=models.CharField(blank=True, max_length=10, verbose_name='일'),
        ),
    ]
