# Generated by Django 3.0.2 on 2020-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0004_auto_20200127_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='onl',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='onl',
            name='date',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='일'),
        ),
        migrations.AlterField(
            model_name='onl',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='월'),
        ),
    ]
