# Generated by Django 3.0.2 on 2020-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0005_auto_20200127_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='onl',
            name='events',
            field=models.TextField(blank=True, max_length=500, verbose_name='사건'),
        ),
    ]
