# Generated by Django 3.0.2 on 2020-02-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0006_onl_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onl',
            options={'ordering': ('month', 'day')},
        ),
        migrations.RenameField(
            model_name='onl',
            old_name='date',
            new_name='day',
        ),
    ]
