# Generated by Django 3.0.2 on 2020-02-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0007_auto_20200202_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='onl',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='날짜'),
        ),
    ]
